services:
  lei:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/lei
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=192.168.254.184
      - DB_NAME=dev_django
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_PORT=5432

  smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'
