# Generated by Django 3.1.2 on 2020-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfgApprovingOfficers',
            fields=[
                ('li_ao_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."cfg_approving_officers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfgAttestingOfficers',
            fields=[
                ('li_ao_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."cfg_attesting_officers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfgCertifyingOfficers',
            fields=[
                ('li_co_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."cfg_certifying_officers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfgGlobal',
            fields=[
                ('li_cg_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(blank=True, max_length=200, null=True)),
                ('val_text', models.TextField(blank=True, null=True)),
                ('val_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('val_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."cfg_global',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfgOfficials',
            fields=[
                ('li_o_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."cfg_officials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CfgPresidingOfficers',
            fields=[
                ('li_po_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."cfg_presiding_officers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegApprovedBy',
            fields=[
                ('li_lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('approved_by_name', models.TextField(blank=True, null=True)),
                ('approved_by_designation', models.TextField(blank=True, null=True)),
                ('approved_by_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."leg_approved_by',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegAttendees',
            fields=[
                ('li_la_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('is_present', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."leg_attendees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegAttestedBy',
            fields=[
                ('li_lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('attested_by_name', models.TextField(blank=True, null=True)),
                ('attested_by_designation', models.TextField(blank=True, null=True)),
                ('attested_by_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."leg_attested_by',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegCertifiedBy',
            fields=[
                ('li_lcb_id', models.AutoField(primary_key=True, serialize=False)),
                ('certified_by_name', models.TextField(blank=True, null=True)),
                ('certified_by_designation', models.TextField(blank=True, null=True)),
                ('certified_by_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."leg_certified_by',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegislativeInfo',
            fields=[
                ('li_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_no', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('edited_by_username', models.CharField(blank=True, max_length=100, null=True)),
                ('whole_text', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('scanned', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."legislative_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegPresidedOverBy',
            fields=[
                ('li_lpob_id', models.AutoField(primary_key=True, serialize=False)),
                ('presided_over_by_name', models.TextField(blank=True, null=True)),
                ('presided_over_by_designation', models.TextField(blank=True, null=True)),
                ('presided_over_by_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."leg_presided_over_by',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverviewLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_id', models.IntegerField(blank=True, null=True)),
                ('res_no_full', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('scanned', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lei"."overview__li',
                'managed': False,
            },
        ),
    ]
