# Generated by Django 3.1.2 on 2020-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('midname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=400, null=True)),
                ('fulladdress', models.TextField(blank=True, null=True)),
                ('address_num', models.CharField(blank=True, max_length=100, null=True)),
                ('address_street', models.CharField(blank=True, max_length=500, null=True)),
                ('address_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('address_block', models.CharField(blank=True, max_length=100, null=True)),
                ('address_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('address_sitio', models.CharField(blank=True, max_length=500, null=True)),
                ('address_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_province', models.CharField(blank=True, max_length=100, null=True)),
                ('address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('address_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no_cp', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('sex_types_id', models.IntegerField(blank=True, null=True)),
                ('profile_share_types_id', models.IntegerField(blank=True, null=True)),
                ('tin', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('work_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=200, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_status_id', models.IntegerField(blank=True, null=True)),
                ('grp_place_of_registration', models.TextField(blank=True, null=True)),
                ('grp_date_of_registration', models.DateField(blank=True, null=True)),
                ('grp_nature_of_business', models.TextField(blank=True, null=True)),
                ('grp_organization_branch', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsCedula',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula_date', models.DateField(blank=True, null=True)),
                ('cedula_place', models.CharField(blank=True, max_length=500, null=True)),
                ('is_issued_here', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons_cedula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsCivilStatus',
            fields=[
                ('pcs_id', models.AutoField(primary_key=True, serialize=False)),
                ('civil_status_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('civil_status_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persons_civil_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsFields',
            fields=[
                ('pf_id', models.AutoField(primary_key=True, serialize=False)),
                ('fields_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persons_fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsFieldsAdditional',
            fields=[
                ('pfa_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_val', models.TextField(blank=True, null=True)),
                ('numeric_val', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('date_val', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons_fields_additional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsFieldStatus',
            fields=[
                ('pfs_id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons_field_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsFieldTypes',
            fields=[
                ('pft_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_types_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persons_field_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsHiddenFields',
            fields=[
                ('phf_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hide_status', models.BooleanField(blank=True, null=True)),
                ('widget_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m_module_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'persons_hidden_fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsModules',
            fields=[
                ('pm_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('module_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persons_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsOrganizationKinds',
            fields=[
                ('pok_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_kind_description', models.TextField(blank=True, null=True)),
                ('organization_kind_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'persons_organization_kinds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsOrganizationMembers',
            fields=[
                ('pom_id', models.AutoField(primary_key=True, serialize=False)),
                ('persons_p', models.IntegerField(blank=True, null=True)),
                ('temp_membership_types_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons_organization_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsOrganizationMembershipTypes',
            fields=[
                ('pmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_types_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('membership_types_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persons_organization_membership_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsProfileShareGroups',
            fields=[
                ('ppsg_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_rights', models.BooleanField(blank=True, null=True)),
                ('is_default_share_type', models.BooleanField(blank=True, null=True)),
                ('temp_profile_share_types_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons_profile_share_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsProfileShareTypes',
            fields=[
                ('ppst_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_share_types_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_share_types_name', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'persons_profile_share_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsSexTypes',
            fields=[
                ('pst_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex_types_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sex_types_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'persons_sex_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsTypes',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('persons_types_name', models.CharField(blank=True, max_length=400, null=True)),
                ('persons_types_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'persons_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_code', models.CharField(max_length=100, unique=True)),
                ('systems_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'systems',
                'managed': False,
            },
        ),
    ]
