# Generated by Django 3.1.2 on 2020-12-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persons',
            table='generic"."persons',
        ),
    ]
